events {}

http {
  client_max_body_size 1G;

  server {
    listen 80;
    server_name lenseiq.com www.lenseiq.com;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name lenseiq.com www.lenseiq.com;

    ssl_certificate /etc/letsencrypt/live/lenseiq.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lenseiq.com/privkey.pem;

    location / {
      proxy_pass http://frontend:3000;
    }

    location /api/ {
      proxy_pass http://backend:8001;
    }

    location /auth/ {
      proxy_pass http://backend:8001;
    }

    location /clips/ {
      proxy_pass http://backend:8001;
    }
  }
}